### PR TITLE
Upgrade to font-awesome 4.7.0

### PR DESCRIPTION
**Pull request by noirbizarre**

### CODE REVIEW

**Comment by alexgleason** [comment]
Awesome, thank you!

**Comment by noirbizarre** [comment]
You're welcome ;)

**Comment by noirbizarre** [comment]
Is it possible to release this change ?

**Comment by alexgleason** [comment]
@noirbizarre Are you on PyPi? If so give me your username and I'll give you access to push releases

**Comment by noirbizarre** [comment]
Yes I am. My username: noirbizarre
Thanks !

**Comment by alexgleason** [comment]
@noirbizarre I added you as an owner. Thanks for contributing!

**Comment by noirbizarre** [comment]
You're welcome !
See #10 for the changes needed to publish.

**Pull request merged**
