### PR TITLE
Fix unicode characters in ASCII source for Bootstrap 4.

### PR DESCRIPTION
**Pull request by FlipperPA**
Include gzip'd version and minify. Update gulpfile and versioning.

### CODE REVIEW

**Comment by alexgleason** [comment]
* What's up with Bootstrap 4?
* What does the gzip feature do?

**Comment by FlipperPA** [comment]
So a few things:

- FontAwesome ships using the Unicode ASCII equivalent code rather than the character itself; this matches the FontAwesome distribution.
- This also minifies the CSS that is created.
- By providing a GZIP'd version, most modern browsers will grab the GZIP'd version instead of the CSS version if it exists with the same file + ".gz": https://github.com/jstuckey/gulp-gzip

I'll show you the issue with italics in person some time. It's an odd one.

**Comment by alexgleason** [comment]
Wonderful, I support this. Thanks!

**Comment by alexgleason** [comment]
@FlipperPA Would you mind deploying this?

**Comment by FlipperPA** [comment]
I'd love to, @alexgleason, but I only have deploy rights for `wagtailerrorpages`, not `wagtailfontawesome`. :) Want to hook me up and I'll take care of it?

**Comment by alexgleason** [comment]
Just added you to it!

**Pull request merged**
