### PR TITLE
Pin FontAwesome version at 4.7

### PR DESCRIPTION
**Pull request by DanielSwain**

### CODE REVIEW

**Comment by alexgleason** [comment]
Nice, thanks! Didn't know you could do that.

**Comment by FlipperPA** [comment]
Am I missing something, or did this just update the README? @alexgleason If you're cool with it, I can do the changes for the versioning.

**Comment by alexgleason** [comment]
The issue raised in #28 was that FA5 icon names didn't work with this package which was confusing since the readme linked to FA5's page. I think FA4 is already pinned in the package.json, so no further action is needed, right?

**Comment by FlipperPA** [comment]
@alexgleason Yes, that's what I figured.

**Pull request merged**
